### ISSUE TITLE
Null exit code on successful run

### ISSUE THREAD

**Issue by testlabauto** [mkatychev/darkroom#9]
Hi, admittedly I don't know rust and can't really follow the code but I was hoping you could shed some light on what I am seeing.  I am using darkroom and occasionally seeing passing reels show a null exit code.  Do you see any way this could be possible?  Should I update my runner script to consider a null exit code to be a pass?

**Comment by mkatychev** [comment]
Hi @testlabauto are you able to provide a minimally working example? grpcbin and httpbin are great places to start. I'm not sure what a null exit code is, could you provide more details? You can `dark record ... && echo $?` to enumerate the exit status of your run, in POSIX an exit code of 0 is considered a success and any other integer is an unsuccessful run.

**Comment by testlabauto** [comment]
Hi @mkatychev, thanks for your response.  Unfortunately, this is hard to reproduce, but I appreciate your feedback nonetheless.  I also don't know what a null exit code is, but that got me thinking: this issue is much more likely coming from the fact that I am running many reels in parallel with node spawn than it is coming from darkroom.  I have just read that spawn will return a null exit code in cases of OOM, for instance.  Please consider this issue closed and thanks for your great tool.

**Comment by mkatychev** [comment]
Of course, happy to help. Please feel free to submit any feature requests/issues and I will get to them as I can.

**Comment by mkatychev** [comment]
'null exit code' is not a darkroom error, the error arose from node.
